import { BikeStation, Bike, RentalHistory } from "@/components";

export const stations: BikeStation[] = [
  {
    id: "station1",
    name: "Library Building",
    availableBikes: 7,
    emptySlots: 8,
    location: {
      latitude: 37.7749,
      longitude: -122.4194,
    },
    distance: 0.2,
  },
  {
    id: "station2",
    name: "College of Sciences and Computing",
    availableBikes: 5,
    emptySlots: 10,
    location: {
      latitude: 37.7750,
      longitude: -122.4180,
    },
    distance: 0.5,
  },
  {
    id: "station3",
    name: "College of Engineering",
    availableBikes: 3,
    emptySlots: 12,
    location: {
      latitude: 37.7752,
      longitude: -122.4170,
    },
    distance: 0.8,
  },
  {
    id: "station4",
    name: "University Hospital",
    availableBikes: 6,
    emptySlots: 9,
    location: {
      latitude: 37.7755,
      longitude: -122.4165,
    },
    distance: 1.0,
  },
  {
    id: "station5",
    name: "College of Arts and Sciences",
    availableBikes: 4,
    emptySlots: 11,
    location: {
      latitude: 37.7748,
      longitude: -122.4175,
    },
    distance: 0.6,
  },
  {
    id: "station6",
    name: "College of Education",
    availableBikes: 2,
    emptySlots: 13,
    location: {
      latitude: 37.7745,
      longitude: -122.4185,
    },
    distance: 0.9,
  },
  {
    id: "station7",
    name: "College of Veterinary Medicine",
    availableBikes: 5,
    emptySlots: 10,
    location: {
      latitude: 37.7742,
      longitude: -122.4190,
    },
    distance: 1.2,
  },
  {
    id: "station8",
    name: "University Market",
    availableBikes: 8,
    emptySlots: 7,
    location: {
      latitude: 37.7753,
      longitude: -122.4188,
    },
    distance: 0.4,
  },
  {
    id: "station9",
    name: "College of Nursing",
    availableBikes: 3,
    emptySlots: 12,
    location: {
      latitude: 37.7747,
      longitude: -122.4198,
    },
    distance: 0.7,
  },
  {
    id: "station10",
    name: "College of Agriculture",
    availableBikes: 4,
    emptySlots: 11,
    location: {
      latitude: 37.7740,
      longitude: -122.4205,
    },
    distance: 1.5,
  },
];

export const bikes: Bike[] = [
  {
    id: "bike1",
    name: "FORDA-EBIKE-1",
    stationId: "station1",
    available: true,
    pricePerHour: 20,
    isElectric: true,
    batteryLevel: 85,
  },
  {
    id: "bike2",
    name: "FORDA-EBIKE-2",
    stationId: "station1",
    available: true,
    pricePerHour: 20,
    isElectric: true,
    batteryLevel: 90,
  },
  {
    id: "bike3",
    name: "FORDA-EBIKE-3",
    stationId: "station2",
    available: true,
    pricePerHour: 20,
    isElectric: true,
    batteryLevel: 75,
  },
  {
    id: "bike4",
    name: "FORDA-EBIKE-4",
    stationId: "station2",
    available: true,
    pricePerHour: 20,
    isElectric: true,
    batteryLevel: 80,
  },
  {
    id: "bike5",
    name: "FORDA-EBIKE-5",
    stationId: "station3",
    available: true,
    pricePerHour: 20,
    isElectric: true,
    batteryLevel: 95,
  },
  {
    id: "bike6",
    name: "FORDA-EBIKE-6",
    stationId: "station4",
    available: true,
    pricePerHour: 20,
    isElectric: false,
    batteryLevel: 0,
  },
  {
    id: "bike7",
    name: "FORDA-EBIKE-7",
    stationId: "station5",
    available: true,
    pricePerHour: 20,
    isElectric: true,
    batteryLevel: 65,
  },
  {
    id: "bike8",
    name: "FORDA-EBIKE-8",
    stationId: "station6",
    available: true,
    pricePerHour: 20,
    isElectric: true,
    batteryLevel: 70,
  },
  {
    id: "bike9",
    name: "FORDA-EBIKE-9",
    stationId: "station7",
    available: true,
    pricePerHour: 20,
    isElectric: false,
    batteryLevel: 0,
  },
  {
    id: "bike10",
    name: "FORDA-EBIKE-10",
    stationId: "station8",
    available: true,
    pricePerHour: 20,
    isElectric: true,
    batteryLevel: 88,
  },
];

export const rentalHistory: RentalHistory[] = [
  {
    id: "rental1",
    bikeId: "bike1",
    bikeName: "Bike #1",
    startTime: "2025-04-12T07:30:00",
    endTime: "2025-04-12T08:30:00",
    startStation: "Library Building",
    endStation: "College of Sciences and Computing",
    duration: "1h 0m",
    cost: 40,
    distance: 2.3,
  },
  {
    id: "rental2",
    bikeId: "bike2",
    bikeName: "Bike #2",
    startTime: "2025-04-13T13:30:00",
    endTime: "2025-04-13T15:50:00",
    startStation: "College of Sciences and Computing",
    endStation: "College of Engineering",
    duration: "2h 20m",
    cost: 80,
    distance: 5.3,
  },
];

export const pricingPlans = [
  { duration: "1 hour", price: 20 },
  { duration: "2 hours", price: 30 },
  { duration: "3 hours", price: 40 },
  { duration: "Open time", price: 40, perHour: true },
];